# Generated by Django 6.0.3 on 2026-03-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('Collection1')              
        """, """
            DELETE FROM store_collection WHERE title='Collection1'
    """)
    ]
